# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aqua < Formula
  desc "Declarative CLI Version manager. Support Lazy Install and Sharable configuration mechanism named Registry. Switch versions seamlessly
"
  homepage "https://github.com/aquaproj/aqua"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aquaproj/aqua/releases/download/v1.3.0/aqua_darwin_arm64.tar.gz"
      sha256 "9402a78a05dee0e81d46e456c42d118ca61d7c938fa28df35f66866ecb20d768"

      def install
        bin.install "aqua"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aquaproj/aqua/releases/download/v1.3.0/aqua_darwin_amd64.tar.gz"
      sha256 "4954f3b7abb65d629884af1bf4576726e6e5d90a1b82d6f054ddeee46b712df1"

      def install
        bin.install "aqua"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aquaproj/aqua/releases/download/v1.3.0/aqua_linux_arm64.tar.gz"
      sha256 "576b1d55f2eff24dda731c09ab1790583c86899fae4a896f606ad33f44d182d6"

      def install
        bin.install "aqua"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aquaproj/aqua/releases/download/v1.3.0/aqua_linux_arm.tar.gz"
      sha256 "9bc18fa395ae37e7fee053aeb691309399b4f087c2959c7bc0e0dde43d3956d6"

      def install
        bin.install "aqua"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aquaproj/aqua/releases/download/v1.3.0/aqua_linux_amd64.tar.gz"
      sha256 "de0fdb201813a9bf56547830c865c3d743ae7e26a87738492b66e32e5bedc5e8"

      def install
        bin.install "aqua"
      end
    end
  end

  test do
    system "#{bin}/aqua --version"
  end
end
