# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aqua < Formula
  desc "Declarative CLI Version manager. Support Lazy Install and Sharable configuration mechanism named Registry. Switch versions seamlessly
"
  homepage "https://github.com/aquaproj/aqua"
  version "2.47.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aquaproj/aqua/releases/download/v2.47.0/aqua_darwin_amd64.tar.gz"
      sha256 "6dd9ffdc66f7b48d1133e22208b4ceb896be213e0247462203b68573e8b9afe4"

      def install
        bin.install "aqua"
        generate_completions_from_executable(bin/"aqua", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aquaproj/aqua/releases/download/v2.47.0/aqua_darwin_arm64.tar.gz"
      sha256 "a03644dd8e91a2428753b26bc37356abe437dea973d9de925b94883391c83211"

      def install
        bin.install "aqua"
        generate_completions_from_executable(bin/"aqua", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aquaproj/aqua/releases/download/v2.47.0/aqua_linux_amd64.tar.gz"
        sha256 "a51c7b624ce7332ac63bf39007eb98913e07794c7ad73fa43bb05886103d4428"

        def install
          bin.install "aqua"
          generate_completions_from_executable(bin/"aqua", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aquaproj/aqua/releases/download/v2.47.0/aqua_linux_arm64.tar.gz"
        sha256 "fcf97f643fafaafc17e7c5c1118870cefe1e96db506ab90117e9a16f4be8a400"

        def install
          bin.install "aqua"
          generate_completions_from_executable(bin/"aqua", "completion", shells: [:bash, :zsh, :fish])
        end
      end
    end
  end

  test do
    system "#{bin}/aqua --version"
  end
end
