# This file was generated by GoReleaser. DO NOT EDIT.
cask "aqua" do
  version "2.58.0"

  on_macos do
    on_intel do
      sha256 "324e6da1ff6ee592f1a1e073de0af89996eb7a743309b38c0062a80d290f417e"
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d6a5dbdfac17a9caa256f87104b9ce716dcd6eb8cbe1c248adb63d24101db21"
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4db66fca1cf9061d18ff1c0abc1cb68ada30e1e2500438ec8a20b72661111be"
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e7fe48e181eb6e310653124562b5b30569f1a29b781da6ee82d902ded25c6dc"
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_linux_arm64.tar.gz"
    end
  end

  name "aqua"
  desc "Declarative CLI Version manager. Support Lazy Install and Sharable configuration mechanism named Registry. Switch versions seamlessly
"
  homepage "https://github.com/aquaproj/aqua"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aqua"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aqua"]
    end
  end

  # No zap stanza required

end
