# This file was generated by GoReleaser. DO NOT EDIT.
cask "aqua" do
  version "2.60.0"

  on_macos do
    on_intel do
      sha256 "a9ce35fe714ff66be97e65b84cd3b7c9a06a32f291011471d6ed4e18814785f6"
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "10950cd31a1cbe39009ce82910be4beccfcdfecbcb64ecda940693acd3ea14f3"
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7616788062355157671e983d68aa7f4c4b2691fbb765280512f245a64523e3ea"
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "695e04849161feced95cda06f37f8032287168b19b6eebf2c75c8fe0069e23d1"
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_linux_arm64.tar.gz"
    end
  end

  name "aqua"
  desc "Declarative CLI Version manager. Support Lazy Install and Sharable configuration mechanism named Registry. Switch versions seamlessly
"
  homepage "https://github.com/aquaproj/aqua"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aqua"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aqua"]
    end
  end

  # No zap stanza required

end
