# This file was generated by GoReleaser. DO NOT EDIT.
cask "aqua" do
  name "aqua"
  desc "Declarative CLI Version manager. Support Lazy Install and Sharable configuration mechanism named Registry. Switch versions seamlessly
"
  homepage "https://github.com/aquaproj/aqua"
  version "2.55.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aqua"

  on_macos do
    on_intel do
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_darwin_amd64.tar.gz"
      sha256 "8af6c717cfa3330fa93a2bdd4fb78d187138334861c8bab427c41351e5456b77"
    end
    on_arm do
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_darwin_arm64.tar.gz"
      sha256 "040857e7f4eec6d468dedbad9a05a2409c2dfe13fc2e69c197f25bddec361793"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_linux_amd64.tar.gz"
      sha256 "4b47965f71afee9bef6ac9ca4515dc2adc4bc1dfe279dceab8126e69ca3a6bc3"
    end
    on_arm do
      url "https://github.com/aquaproj/aqua/releases/download/v#{version}/aqua_linux_arm64.tar.gz"
      sha256 "75bef0c9e82480adb4c203b71b9af530945fda60b91f6f860b17791adf068158"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aqua"]
    end
  end

  # No zap stanza required
end
